/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OksidiSharer {
        "css": string;
        "locale": "fi" | "en";
        "shareTitle": string;
        "shareUrl": string;
        "textCopy": string;
        "textShare": string;
        "useEmail": boolean;
        "useFacebook": boolean;
        "useLink": boolean;
        "useLinkedin": boolean;
        "useTwitter": boolean;
        "useWhatsapp": boolean;
    }
}
declare global {
    interface HTMLOksidiSharerElement extends Components.OksidiSharer, HTMLStencilElement {
    }
    var HTMLOksidiSharerElement: {
        prototype: HTMLOksidiSharerElement;
        new (): HTMLOksidiSharerElement;
    };
    interface HTMLElementTagNameMap {
        "oksidi-sharer": HTMLOksidiSharerElement;
    }
}
declare namespace LocalJSX {
    interface OksidiSharer {
        "css"?: string;
        "locale"?: "fi" | "en";
        "shareTitle"?: string;
        "shareUrl"?: string;
        "textCopy"?: string;
        "textShare"?: string;
        "useEmail"?: boolean;
        "useFacebook"?: boolean;
        "useLink"?: boolean;
        "useLinkedin"?: boolean;
        "useTwitter"?: boolean;
        "useWhatsapp"?: boolean;
    }
    interface IntrinsicElements {
        "oksidi-sharer": OksidiSharer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "oksidi-sharer": LocalJSX.OksidiSharer & JSXBase.HTMLAttributes<HTMLOksidiSharerElement>;
        }
    }
}
